# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

dependencies:
  - name: gitpod
    version: "0.4.0"
    repository: "file://../../gitpod-core/chart/"