# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

gitpod:
  # This field must be set to your domain name. Leaving it set to its default value will result in
  # a non-functional installation.
  hostname: your-domain.com

  # If you have a static IP that your domain resolves to, set it here.
  # Leaving this field set to its default value is fine. Kubernetes will assign you an IP address
  # during deployment.
  components:
    proxy:
      loadBalancerIP: null

  # Gitpod needs at least one auth provider to allow users to log in.
  # The auth providers below are examples only. Please change/remove them to fit your installation.
  authProviders:
  - id: "Example GitHub"
    host: "github.com"
    type: "GitHub"
    oauth:
      clientId: "your-client-ID-here"
      clientSecret: "your-client-secret-here"
      callBackUrl: "https://your-domain.com/auth/github/callback"
      settingsUrl: "https://github.com/settings/connections/applications/your-client-ID-here"
  - id: "Example Gitlab"
    host: "gitlab.com"
    type: "GitLab"
    oauth:
      clientId: "your-application-ID-here"
      clientSecret: "your-secret-here"
      callBackUrl: "https://your-domain.com/auth/gitlab/callback"
      settingsUrl: "gitlab.com/profile/applications"

  # RBAC is enabled by default. If your cluster does not use RBAC, set this flag to false so that
  # we do not attempt to install PodSecurityPolicies and the likes.
  installPodSecurityPolicies: true
