---
- name: Install yq
  get_url:
    url: https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    dest: /usr/local/bin/yq
    mode: 0755
  become: true

- name: Download Gitpod installer
  get_url:
    url: https://github.com/gitpod-io/gitpod/releases/download/2022.01/gitpod-installer-linux-amd64
    dest: /usr/local/bin/gitpod-installer
    checksum: sha256:0a03b767fcc4be1806ddbac799e49e0b22f99a578ceed6461296952f2db9c1dd
    mode: 0755
  become: true

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  become: true
  loop:
    - /gitpod

- name: Generate Gitpod config
  shell: gitpod-installer init > /gitpod/gitpod-config.yaml

- name: Get manifest files
  find:
    path: /gitpod/manifests
    patterns: '*.yaml'
    file_type: file
  register: manifest_files

- name: Remove uid and resource version from manifests files
  shell: |
    yq eval --inplace "del(.metadata.uid)" "{{ item.path }}"
    yq eval --inplace "del(.metadata.resourceVersion)" "{{ item.path }}"
  with_items: "{{ manifest_files.files }}"

- name: Get auth-provider files
  find:
    path: /gitpod/manifests
    patterns: 'auth-provider*.yaml'
    file_type: file
  register: auth_provider_files

- name: Add auth-providers to Gitpod config
  command: 'yq eval --inplace ".authProviders += [{\"kind\": \"secret\", \"name\": \"{{ item.path | basename | splitext | first }}\"}]" /gitpod/gitpod-config.yaml'
  with_items: "{{ auth_provider_files.files }}"
