# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License.MIT.txt in the project root for license information.

apiVersion: v1
kind: Secret
metadata:
  name: https-certificates
  labels:
    app: gitpod
    component: gitpod-installer
  annotations:
    kots.io/when: '{{repl ConfigOptionEquals "cert_manager_enabled" "0" }}'
type: kubernetes.io/tls
data:
  tls.crt: '{{repl ConfigOption "tls_crt" }}'
  tls.key: '{{repl ConfigOption "tls_key" }}'
