apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: https-certificates
  annotations:
    kots.io/when: '{{repl or (ConfigOptionEquals "tls_self_signed_enabled" "1") (ConfigOptionEquals "cert_manager_enabled" "1") }}'
spec:
  secretName: https-certificates
  issuerRef:
    name: '{{repl if (ConfigOptionEquals "tls_self_signed_enabled" "1" ) }}ca-issuer{{repl else }}gitpod-issuer{{repl end }}'
    kind: Issuer
  dnsNames:
    - '{{repl ConfigOption "domain" }}'
    - '*.{{repl ConfigOption "domain" }}'
    - '*.ws.{{repl ConfigOption "domain" }}'
