# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

# This exists as debug information for the support bundle
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitpod-installation
  labels:
    app: gitpod
    component: gitpod-installer
data:
  channelName: repl{{ ChannelName | quote }}
  cursor: repl{{ Cursor | quote }}
  isAirgap: repl{{ IsAirgap | quote }}
  kotsVersion: repl{{ KotsVersion | quote }}
  releaseNotes: repl{{ ReleaseNotes | quote }}
  sequence: repl{{ Sequence | quote }}
  version: repl{{ VersionLabel | quote }}
