# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: installation-status
  labels:
    app: gitpod
    component: gitpod-installer-status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitpod
      component: gitpod-installer-status
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gitpod
        component: gitpod-installer-status
    spec:
      restartPolicy: Always
      serviceAccountName: installer
      containers:
        - name: installation-status
          # This will normally be the release tag
          image: "eu.gcr.io/gitpod-core-dev/build/installer:sje-azure-minio-gateway.0"
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -e

              while true
              do
                echo "Checking installation status"

                if [ "$(helm status -n {{repl Namespace }} gitpod -o json | jq '.info.status == "deployed"')" != "true" ];
                then
                  echo "Gitpod: Installation not complete"
                  exit 1
                fi

                echo "Sleeping for 10 seconds"
                sleep 10
              done
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
