# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License.MIT.txt in the project root for license information.

apiVersion: v1
kind: Secret
metadata:
  name: http-proxy-settings
  labels:
    app: gitpod
    component: gitpod-installer
type: Opaque
data:
  httpProxy: repl{{ HTTPProxy | Base64Encode | quote }}
  httpsProxy: repl{{ HTTPSProxy | Base64Encode | quote }}
  noProxy: repl{{ printf "kotsadm,.%s,%s" (ConfigOption "domain") (NoProxy) | Base64Encode | quote }}
