# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License.MIT.txt in the project root for license information.

apiVersion: v1
kind: Secret
metadata:
  name: custom-registry-credentials
  annotations:
    kots.io/when: '{{repl ConfigOptionEquals "reg_docker_config_enable" "1" }}'
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: repl{{ ConfigOptionData "reg_docker_config" | Base64Encode | quote }}
