# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License.MIT.txt in the project root for license information.

apiVersion: v1
kind: Secret
metadata:
  name: storage-gcp
  labels:
    app: gitpod
    component: gitpod-installer
  annotations:
    kots.io/when: '{{repl ConfigOptionEquals "store_provider" "gcp" }}'
data:
  service-account.json: '{{repl ConfigOption "store_gcp_credentials" }}'
