# Copyright (c) 2023 Gitpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License.AGPL.txt in the project root for license information.

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: https-certificates
  labels:
    app: gitpod
    component: gitpod-installer
  annotations:
    kots.io/when: '{{repl or (ConfigOptionEquals "tls_self_signed_enabled" "1") (ConfigOptionEquals "cert_manager_enabled" "1") }}'
spec:
  secretName: https-certificates
  issuerRef:
    name: '{{repl if (ConfigOptionEquals "tls_self_signed_enabled" "1" ) }}ca-issuer{{repl else }}{{repl ConfigOption "cert_manager_issuer_name" }}{{repl end }}'
    kind: '{{repl if (ConfigOptionEquals "tls_self_signed_enabled" "1" ) }}Issuer{{repl else }}{{repl ConfigOption "cert_manager_issuer" }}{{repl end }}'
  dnsNames:
    - '{{repl ConfigOption "domain" }}'
    - '*.{{repl ConfigOption "domain" }}'
    - '*.ws.{{repl ConfigOption "domain" }}'
  secretTemplate:
    labels:
      app: gitpod
      component: gitpod-installer
      kots.io/app-slug: '{{repl LicenseFieldValue "appSlug" }}'
      kots.io/backup: velero
