# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: fluent-bit
spec:
  chart:
    name: fluent-bit
    chartVersion: 0.20.2
  helmVersion: v3
  useHelmInstall: true
  weight: 10
  values:
    fluent-bit:
      extraVolumes:
        - name: collector
          hostPath:
            path: /gitpod
            type: DirectoryOrCreate

      extraVolumeMounts:
        - name: collector
          mountPath: /gitpod

      extraContainers:
        - name: kots
          image: busybox:1
          command:
            - sh
            - -c
          args:
            - while true; do echo "waiting" && sleep 60; done
          volumeMounts:
            - name: collector
              mountPath: /gitpod
              readOnly: true

      labels:
        app: gitpod
        component: gitpod-log-collector

      podLabels:
        app: gitpod
        component: gitpod-log-collector

      # Config requires four space indentations
      config:
        inputs: |
          [INPUT]
              Name tail
              Path /var/log/containers/*.log
              Parser docker
              Tag <pod_name>.<container_name>
              Tag_Regex (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
              Skip_Long_Lines On

        filters: |
          [FILTER]
              Name stdout

        outputs: |
          [OUTPUT]
              Name file
              Match imagebuild*
              Mkdir true
              Path /gitpod/log-collector
              Format plain

          [OUTPUT]
              Name file
              Match installer*
              Mkdir true
              Path /gitpod/log-collector
              Format plain

          # Workspaces
          [OUTPUT]
              Name file
              Match ws*.workspace
              Mkdir true
              Path /gitpod/log-collector
              Format plain
