# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License.MIT.txt in the project root for license information.

apiVersion: v1
kind: Secret
metadata:
  name: storage-s3
  labels:
    app: gitpod
    component: gitpod-installer
  annotations:
    kots.io/when: '{{repl ConfigOptionEquals "store_provider" "s3" }}'
data:
  accessKeyId: '{{repl ConfigOption "store_s3_access_key_id" | Base64Encode }}'
  secretAccessKey: '{{repl ConfigOption "store_s3_secret_access_key" | Base64Encode }}'
