# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: v1
kind: ConfigMap
metadata:
  name: gitpod-kots-config
  labels:
    app: gitpod
    component: gitpod-installer
data:
  # KOTS settings
  GITPOD_INSTALLER_CONFIG: /tmp/gitpod-config.yaml
  GITPOD_OBJECTS: /tmp/gitpod

  # General settings
  CURSOR: repl{{ Cursor | quote }}
  DISTRIBUTION: repl{{ Distribution | quote }}
  DOMAIN: repl{{ ConfigOption "domain" | quote }}
  NAMESPACE: repl{{ Namespace | quote }}
  OPEN_VSX_URL: repl{{ ConfigOption "openVsxUrl" | quote }}
  SSH_GATEWAY: repl{{ ConfigOption "ssh_gateway" | quote }}

  # Secret names
  HTTP_PROXY_NAME: '{{repl if (ConfigOptionEquals "enable_proxy_settings" "1" ) }}http-proxy-settings{{repl end }}'
  LICENSE_NAME: gitpod-license
  SSH_GATEWAY_HOST_KEY_NAME: ssh-gateway-host-key

  # Database settings
  DB_INCLUSTER_ENABLED: repl{{ ConfigOption "db_incluster" | quote }}
  DB_CLOUDSQL_ENABLED: repl{{ ConfigOption "db_cloudsql_enabled" | quote }}
  DB_CLOUDSQL_INSTANCE: repl{{ ConfigOption "db_cloudsql_instance" | quote }}
  DB_CLOUDSQL_SERVICE_ACCOUNT_NAME: cloudsql
  DB_EXTERNAL_CERTIFICATE_NAME: database

  # Airgap settings
  HAS_LOCAL_REGISTRY: repl{{ HasLocalRegistry | quote }}
  LOCAL_REGISTRY_ADDRESS: repl{{ LocalRegistryAddress | quote }}
  LOCAL_REGISTRY_HOST: repl{{ LocalRegistryHost | quote }}
  IMAGE_PULL_SECRET_NAME: repl{{ ImagePullSecretName | quote }}

  # Registry settings
  REGISTRY_INCLUSTER_ENABLED: repl{{ ConfigOption "reg_incluster" | quote }}
  REGISTRY_URL: repl{{ ConfigOption "reg_url" | quote }}
  REGISTRY_INCLUSTER_STORAGE: repl{{ ConfigOption "reg_incluster_storage" | quote }}
  REGISTRY_INCLUSTER_STORAGE_S3_REGION: repl{{ ConfigOption "reg_incluster_storage_s3_region" | quote }}
  REGISTRY_INCLUSTER_STORAGE_S3_ENDPOINT: repl{{ ConfigOption "reg_incluster_storage_s3_endpoint" | quote }}
  REGISTRY_INCLUSTER_STORAGE_S3_BUCKET_NAME: repl{{ ConfigOption "reg_incluster_storage_s3_bucketname" | quote }}
  REGISTRY_INCLUSTER_STORAGE_S3_CERTIFICATE_NAME: container-registry-s3-backend
  REGISTRY_DOCKER_CONFIG_ENABLED: repl{{ ConfigOption "reg_docker_config_enable" | quote }}
  REGISTRY_EXTERNAL_CERTIFICATE_NAME: container-registry

  # Storage settings
  STORE_PROVIDER: repl{{ ConfigOption "store_provider" | quote }}
  STORE_REGION: repl{{ ConfigOption "store_region" | quote }}
  STORE_GCP_PROJECT: repl{{ ConfigOption "store_gcp_project" | quote }}
  STORE_S3_ENDPOINT: repl{{ ConfigOption "store_s3_endpoint" | quote }}
  STORE_S3_BUCKET: repl{{ ConfigOption "store_s3_bucket" | quote }}
  STORE_AZURE_CREDENTIALS_NAME: storage-azure
  STORE_GCP_SERVICE_ACCOUNT_NAME: storage-gcp
  STORE_S3_CREDENTIALS_NAME: storage-s3

  # TLS certificate settings
  CERT_MANAGER_ENABLED: repl{{ ConfigOption "cert_manager_enabled" | quote }}
  TLS_SELF_SIGNED_ENABLED: repl{{ ConfigOption "tls_self_signed_enabled" | quote }}
  TLS_CUSTOM_CA_CRT_ENABLED: repl{{ ConfigOptionNotEquals "tls_ca_crt" "" | quote }} # Use comparison not value
  TLS_CUSTOM_CA_CRT_CREDENTIALS_NAME: ca-certificate

  # User management settings
  USER_MANAGEMENT_BLOCK_ENABLED: repl{{ ConfigOption "user_management_block_enabled" | quote }}
  USER_MANAGEMENT_BLOCK_PASSLIST: repl{{ ConfigOption "user_management_block_passlist" | quote }}

  # Advanced settings
  ADVANCED_MODE_ENABLED: repl{{ ConfigOption "advanced_mode_enabled" | quote }}
  COMPONENT_PROXY_SERVICE_TYPE: repl{{ ConfigOption "component_proxy_service_serviceType" | quote }}
  CUSTOMIZATION_PATCH_ENABLED: repl{{ ConfigOptionNotEquals "customization_patch" "" | quote }} # Use comparison not value
  INSTALLER_TIMEOUT: repl{{ ConfigOption "installer_timeout" | quote }}

  # Customizations
  CONFIG_PATCH: repl{{ ConfigOptionData "config_patch" | default "" | quote }}
  CUSTOMIZATION_PATCH: repl{{ ConfigOptionData "customization_patch" | default "" | quote }}
