apiVersion: v1
kind: Secret
metadata:
  name: cloudsql
  labels:
    app: gitpod
    component: gitpod-installer
  annotations:
    kots.io/when: '{{repl and (ConfigOptionEquals "db_incluster" "0") (ConfigOptionEquals "db_cloudsql_enabled" "1") }}'
data:
  credentials.json: '{{repl ConfigOption "db_gcp_credentials" }}'
  encryptionKeys: '{{repl ConfigOption "db_encryption_keys" | Base64Encode }}'
  password: '{{repl ConfigOption "db_password" | Base64Encode }}'
  username: '{{repl ConfigOption "db_username" | Base64Encode }}'
