# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: installation-status
  labels:
    app: gitpod
    component: gitpod-installer-status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitpod
      component: gitpod-installer-status
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gitpod
        component: gitpod-installer-status
    spec:
      restartPolicy: Always
      serviceAccountName: kotsadm
      containers:
        - name: installation-status
          # This will normally be the release tag
          image: "eu.gcr.io/gitpod-core-dev/build/installer:sje-installer-fixes.0"
          envFrom:
            - configMapRef:
                name: gitpod-kots-config
          command:
            - /app/scripts/kots-installation-status.sh
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
