# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup
  annotations: {}
spec: {}
