## start with
##    loadgen benchmark prod-benchmark-pvc.yaml

workspaces: 1
ideImage: eu.gcr.io/gitpod-core-dev/build/ide/code:commit-b86bfcbb01feb0b9c3e67a14e6ad3bb95044f51d
waitForRunning: "600s"
waitForStopping: "600s"
successRate: 1
environment:
  - name: "THEIA_SUPERVISOR_TOKENS"
    value: '[{"token":"foobar","host":"gitpod-staging.com","scope":["function:getWorkspace","function:getLoggedInUser","function:getPortAuthenticationToken","function:getWorkspaceOwner","function:getWorkspaceUsers","function:isWorkspaceOwner","function:controlAdmission","function:setWorkspaceTimeout","function:getWorkspaceTimeout","function:sendHeartBeat","function:getOpenPorts","function:openPort","function:closePort","function:getLayout","function:generateNewGitpodToken","function:takeSnapshot","function:storeLayout","function:stopWorkspace","resource:workspace::fa498dcc-0a84-448f-9666-79f297ad821a::get/update","resource:workspaceInstance::e0a17083-6a78-441a-9b97-ef90d6aff463::get/update/delete","resource:snapshot::*::create/get","resource:gitpodToken::*::create","resource:userStorage::*::create/get/update"],"expiryDate":"2020-12-01T07:55:12.501Z","reuse":2}]'
workspaceClass: "g1-standard-pvc"
featureFlags:
# https://github.com/gitpod-io/gitpod/blob/e437e1868072dfad1d195031a4709a254bd60dc8/components/ws-manager-api/core.proto#L596
# from core.proto: PERSISTENT_VOLUME_CLAIM = 7;
  #- 7
repos:
  - cloneURL: https://github.com/Furisto/workspace-stress
    cloneTarget: main
    score: 0
    workspaceImage: eu.gcr.io/gitpod-dev/dev/loadtest/workspace-stress:latest
    environment:
    # cpu
    - name: "CPU_COUNT" # start N workers
      value: "3"
    - name: "CPU_BACKOFF" # wait N microseconds between the start of each stress worker process
      value: "10000000"
    - name: "CPU_TIMEOUT" # stop cpu stress test after N seconds
      value: "600s"
    # common IO
    - name: "DISK_IO_FILE_SIZE" # how big of a test-file should be used
      value: "2g"
    - name: "DISK_IO_TOTAL" # specifies how much I/O will be done
      value: "100g"
    - name: "DISK_IO_TIMEOUT" # stop io stress test after N seconds
      value: "600"
    # random read/write IO
    # - name: DISK_IO_MODE # values can be read, write, rw, randreadm randwrite, randrw
    #   value: "randrw"
    # - name: "DISK_IO_BLOCKSIZE" # specifies the block-size that will be used
    #   value: "8k"
    # - name: "DISK_IO_FSYNC" # sync command which writes kernel cached pages to disk every number of blocks specified
    #   value: 1000
    # - name: "DISK_IO_DEPTH" # specifies number of I/O units to keep in-flight
    #   value: 10
    # - name: "DISK_IO_JOBS" # specifies the number of jobs
    #   value: 20
    # sequential read/write IO
    - name: DISK_IO_MODE # values can be read, write, rw, randreadm randwrite, randrw
      value: "rw"
    - name: "DISK_IO_BLOCKSIZE" # specifies the block-size that will be used
      value: "1024k"
    - name: "DISK_IO_FSYNC" # sync command which writes kernel cached pages to disk every number of blocks specified
      value: 10000
    - name: "DISK_IO_DEPTH" # specifies number of I/O units to keep in-flight
      value: 32
    - name: "DISK_IO_JOBS" # specifies the number of jobs
      value: 1
    # memory
    - name: "MEMORY_BYTES" # systems if not enough physical memory and swap is not available
      value: "6G"
    - name: "MEMORY_TIMEOUT" # stop cpu stress test after N seconds
      value: "600s"
    # backup
    - name: "BACKUP_SIZE" # size of the backup in gigabyte
      value: 12
    # tasks
    - name: "GITPOD_TASKS"
      value: "[{\"name\":\"start cpu stress\",\"command\":\"stress-ng --cpu ${CPU_COUNT:-3} --backoff ${CPU_BACKOFF:-10000000} --timeout ${CPU_TIMEOUT:-600s}\"},{\"name\":\"start io stress\",\"command\":\"fio --name io-stress --eta-newline=5s --filename=/workspace/gitpod.temp --rw=${DISK_IO_MODE} --size=${DISK_IO_FILE_SIZE:-2g} --io_size=${DISK_IO_TOTAL:-50g} --blocksize=${DISK_IO_BLOCKSIZE} --ioengine=libaio --fsync=${DISK_IO_FSYNC} --iodepth=${DISK_IO_DEPTH} --direct=1 --numjobs=${DISK_IO_JOBS} --runtime=${DISK_IO_TIMEOUT:-600}\"},{\"name\":\"start memory stress\",\"command\":\"stress-ng --vm 1 --vm-keep --vm-bytes ${MEMORY_BYTES:-6G} --timeout ${MEMORY_TIMEOUT:-600s}\"},{\"name\":\"create backup file\",\"command\":\"dd if=/dev/zero of=/workspace/benchmark-backup bs=1000M count=${BACKUP_SIZE:-2}\"}]"
  - cloneURL: https://github.com/gitpod-io/template-typescript-node
    cloneTarget: master
    score: 0
    workspaceImage: eu.gcr.io/gitpod-dev/workspace-images:dd3075638ccf424374cc9c681b3d2338908d07115b28e54856cd45604c33768c
    workspaceClass: "g1-large-pvc"
  - cloneURL: https://github.com/gitpod-io/template-typescript-react
    cloneTarget: main
    score: 0
    workspaceImage: eu.gcr.io/gitpod-dev/workspace-images:e764b1a602dc4123d9a027358367b5c4a35b62043e3c630731702144b7d37f77
    workspaceClass: "g1-large-pvc"
  - cloneURL: https://github.com/gitpod-io/template-python-django
    cloneTarget: main
    score: 20
    workspaceImage: eu.gcr.io/gitpod-dev/workspace-images:e764b1a602dc4123d9a027358367b5c4a35b62043e3c630731702144b7d37f77
  - cloneURL: https://github.com/gitpod-io/template-python-flask
    score: 0
    cloneTarget: main
    workspaceImage: eu.gcr.io/gitpod-core-dev/build/workspace-images:b22358e04de57d29fdcc2dd4cf10a7144e6965af16c5eec793ed37dfe7daa03b
