# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ if (index .Values "docker-registry" "enabled") }}
{{- $regName := include "gitpod.builtinRegistry.name" . -}}
{{ $certManager := (index .Values "cert-manager") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: builtin-registry-certs
spec:
  secretName: builtin-registry-certs
  dnsNames: {{ ( list $regName ) | toJson }}
  issuerRef:
    name: {{ $certManager.ca.issuerName }}
    kind: Issuer
    group: cert-manager.io
{{- end }}
