# Copyright (c) 2021 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ $comp := .Values.components.proxy -}}
{{ $certManager := (index .Values "cert-manager") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: proxy-config-certificates
spec:
  secretName: proxy-config-certificates
  commonName: {{ .Values.hostname | quote }}
  dnsNames:
    - {{ .Values.hostname | quote }}
    - "*.{{ .Values.hostname }}"
    - "*.ws{{- if .Values.installation.shortname -}}-{{ .Values.installation.shortname }}{{- end -}}.{{ .Values.hostname }}"
    {{- range $index, $dnsName := $certManager.certificate.additionalNames }}
    - {{ $dnsName | quote }}
    {{ end -}}
  {{- if $comp.certManager }} {{/*  custom proxy certificate issuer */}}
  {{ if $comp.certManager.issuerRef }} {{/*  use custom issuer */}}
  issuerRef: {{ $comp.certManager.issuerRef }}
  {{ else }}
  issuerRef:
    name: {{ if $comp.certManager.issuerName }}{{$comp.certManager.issuerName}}{{ else }}gitpod{{ end }}
    kind: {{ if $comp.certManager.issuerKind }}{{$comp.certManager.issuerKind}}{{ else }}Issuer{{ end }}
    group: cert-manager.io
  {{ end }}
  {{ else }}
  issuerRef:
    name: gitpod
    kind: Issuer
    group: cert-manager.io
  {{ end }}
