# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ if .Values.installPodSecurityPolicies -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-ns-nobody
  labels:
    app: {{ template "gitpod.fullname" . }}
    component: cluster
    kind: role-binding
    stage: {{ .Values.installation.stage }}
subjects:
- kind: ServiceAccount
  name: nobody
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}-ns-psp:unprivileged
  apiGroup: rbac.authorization.k8s.io
{{- end -}}