# Copyright (c) 2021 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ if .Values.installNetworkPolicies -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: content-service
  labels:
    app: {{ template "gitpod.fullname" . }}
    component: content-service
    kind: networkpolicy
    stage: {{ .Values.installation.stage }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "gitpod.fullname" . }}
      component: content-service
  policyTypes:
  - Ingress
  ingress:
  - {}
{{- end -}}
