# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: db-migrations
  labels:
    app: {{ template "gitpod.fullname" . }}
    component: db
    kind: role-binding
    stage: {{ .Values.installation.stage }}
subjects:
- kind: ServiceAccount
  name: db-migrations
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}-ns-psp:restricted-root-user
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: gitpod
    component: migrations
  name: listAndGetPods-migrations
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ListAndGetPods
subjects:
- kind: ServiceAccount
  name: db-migrations
