# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ $comp := .Values.components.db }}
{{- $this := dict "root" . "gp" $.Values "comp" $comp -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: database-sessions
  labels:
    app: {{ template "gitpod.fullname" . }}
    component: database-sessions
    kind: job
    stage: {{ .Values.installation.stage }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    # see https://github.com/helm/helm/blob/master/docs/charts_hooks.md
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-delete-timeout": "0"
spec:
  template:
    metadata:
      name: database-sessions
      labels:
        app: {{ template "gitpod.fullname" . }}
        component: database-sessions
        kind: job
        stage: {{ .Values.installation.stage }}
    spec:
{{ include "gitpod.pod.affinity" $this | indent 6 }}
      restartPolicy: Never
      serviceAccountName: db
      imagePullSecrets:
      enableServiceLinks: false
      containers:
      - name: database-sessions
        image: mysql:5.7.34
        env:
        - name: "MYSQL_PWD"
          value: "{{ $.Values.db.password }}"
        - name: "DB_PORT"
          value: "{{ $.Values.db.port }}"
        - name: "DB_HOST"
          value: "{{ $.Values.db.host }}"
        command: ["sh","-c","mysql -h $DB_HOST --port $DB_PORT -u gitpod < /db-init-scripts/init.sql"]
        volumeMounts:
        - name: db-init-scripts
          mountPath: "/db-init-scripts"
          readOnly: true
      volumes:
      - name: db-init-scripts
        configMap:
          name: db-init-scripts
