# Copyright (c) 2021 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ if not .Values.components.openVsxProxy.disabled -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openvsx-proxy
  labels:
    app: {{ template "gitpod.fullname" . }}
    component: openvsx-proxy
    kind: role-binding
    stage: {{ .Values.installation.stage }}
subjects:
- kind: ServiceAccount
  name: openvsx-proxy
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}-ns-psp:restricted-root-user
  apiGroup: rbac.authorization.k8s.io
{{- end }}

---

{{ if not .Values.components.openVsxProxy.disabled -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-openvsx-proxy-kube-rbac-proxy
  labels:
    app: {{ template "gitpod.fullname" . }}
    component: openvsx-proxy
    kind: role-binding
    stage: {{ .Values.installation.stage }}
subjects:
- kind: ServiceAccount
  name: openvsx-proxy
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name:  {{ .Release.Namespace }}-kube-rbac-proxy
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
