# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ $comp := .Values.components.registryFacade -}}
{{- if not $comp.disabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-facade-config
  labels:
    app: {{ template "gitpod.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.json: |-
    {
        {{ if .Values.components.workspace.pullSecret.secretName -}}"dockerAuth": "/mnt/pull-secret.json",{{- end }}
        "registry": {
            "port": {{ $comp.ports.registry.containerPort }},
            {{- if (or .Values.certificatesSecret.secretName $comp.certificatesSecret.secretName) }}
            {{- if (or .Values.certificatesSecret.certManager $comp.certificatesSecret.certManager) }}
            "tls": {
                "crt": "/mnt/certificates/tls.crt",
                "key": "/mnt/certificates/tls.key"
            },
            {{ else -}}
            "tls": {
                "crt": "/mnt/certificates/fullchain.pem",
                "key": "/mnt/certificates/privkey.pem"
            },
            {{ end -}}
            {{ end -}}
            "theiaLayer": {
                "repo": "{{ template "gitpod.comp.imageRepo" (dict "root" . "gp" $.Values "comp" .Values.components.workspace.theiaImage) }}",
                "defaultVersion": "{{ .Values.version }}"
            },
            "remoteSpecProvider": {
                "addr": "ws-manager:{{ .Values.components.wsManager.ports.rpc.containerPort }}"
            },
            "store": "/mnt/cache/registry",
            "requireAuth": false
        },
        "pprofAddr": ":6060",
        "prometheusAddr": ":9500"
        {{- if not $comp.blobserve.disabled }}
        , "blobserve": {
            "port": {{ $comp.blobserve.ports.service.containerPort }},
            "timeout": {{ ($comp.blobserve.timeout | default "5s") | quote }},
            "mapping": {
                "theia": {
                    "repo": "{{ template "gitpod.comp.imageRepo" (dict "root" . "gp" $.Values "comp" .Values.components.workspace.theiaImage) }}",
                    "workdir": "/theia/node_modules/@gitpod/gitpod-ide/lib"
                }
            },
            "blobSpace": {
                "location": "/mnt/cache/blobserve",
                "maxSizeBytes": {{ $comp.blobserve.maxCacheSize | default 1073741824 }}
            }
        }
        {{ end }}
    }
{{- end -}}