# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: registry-facade
  labels:
    app: {{ template "gitpod.fullname" . }}
    component: registry-facade
    kind: role-binding
    stage: {{ .Values.installation.stage }}
subjects:
- kind: ServiceAccount
  name: registry-facade
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}-ns-psp:restricted-root-user
  apiGroup: rbac.authorization.k8s.io
