# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: server
  labels:
    app: {{ template "gitpod.fullname" . }}
    component: server
    kind: role-binding
    stage: {{ .Values.installation.stage }}
subjects:
- kind: ServiceAccount
  name: server
roleRef:
  kind: Role
  name: server
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-server-rb-kube-rbac-proxy
  labels:
    app: {{ template "gitpod.fullname" . }}
    component: server
    kind: role-binding
    stage: {{ .Values.installation.stage }}
subjects:
- kind: ServiceAccount
  name: server
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name:  {{ .Release.Namespace }}-kube-rbac-proxy
  apiGroup: rbac.authorization.k8s.io
