# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ $comp := .Values.components.wsDaemon -}}
{{- $this := dict "root" . "gp" $.Values "comp" $comp -}}
{{- if not $comp.disabled -}}
{{- $altNames := list ( printf "%s.%s" (include "gitpod.fullname" .) .Release.Namespace ) ( printf "%s.%s.svc" "ws-daemon" .Release.Namespace ) ( printf "wsdaemon" ) -}}

{{ $certManager := (index .Values "cert-manager") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ws-daemon-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: ws-daemon-tls
  dnsNames: {{ $altNames | toJson }}
  issuerRef:
    name: {{ $certManager.ca.issuerName }}
    kind: Issuer
    group: cert-manager.io
{{- end }}
