# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ $comp := .Values.components.wsDaemon -}}
{{- $this := dict "root" . "gp" $.Values "comp" $comp -}}
{{- if not $comp.disabled -}}
{{- $altNames := list ( printf "%s.%s" (include "gitpod.fullname" .) .Release.Namespace ) ( printf "%s.%s.svc" "ws-daemon" .Release.Namespace ) ( printf "wsdaemon" ) -}}
{{ $cm := (index .Values "cert-manager") }}
{{- if $cm.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ws-daemon-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: ws-daemon-tls
  dnsNames: {{ $altNames | toJson }}
  issuerRef:
    name: {{ $cm.ca.issuerName }}
    kind: Issuer
    group: cert-manager.io
{{- else }}
{{- $ca := genCA "wsdaemon-ca" 365 -}}
{{- $cert := genSignedCert (include "gitpod.fullname" . ) nil $altNames 365 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: ws-daemon-tls
  labels:
    app: {{ template "gitpod.fullname" $ }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    checksum/checksd-config: {{ $cert.Cert | indent 2 | sha256sum }}
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
{{- end }}