# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ $comp := .Values.components.wsManager -}}
{{- $this := dict "root" . "gp" $.Values "comp" $comp -}}
{{- if not $comp.disabled -}}
{{- $serverAltNames := list ( printf "%s.%s" (include "gitpod.fullname" .) .Release.Namespace ) ( printf "%s.%s.svc" "ws-manager" .Release.Namespace ) "ws-manager" "ws-manager-dev" -}}
{{- $clientAltNames := list "registry-facade" "server" "ws-manager-bridge" "ws-scheduler" "ws-proxy" "ws-manager" -}}
{{- $server := $comp.tls.server }}
{{- $client := $comp.tls.client }}

{{ $certManager := (index .Values "cert-manager") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $server.secretName }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "gitpod.fullname" $ }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  secretName: "{{ $server.secretName }}"
  dnsNames: {{ $serverAltNames | toJson }}
  issuerRef:
    name: {{ $certManager.ca.issuerName }}
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $client.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "gitpod.fullname" $ }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  secretName: "{{ $client.secretName }}"
  dnsNames: {{ $clientAltNames | toJson }}
  issuerRef:
    name: {{ $certManager.ca.issuerName }}
    kind: Issuer
    group: cert-manager.io
{{ end }}
