# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ $comp := .Values.components.wsManager -}}
{{- $this := dict "root" . "gp" $.Values "comp" $comp -}}
{{- if not $comp.disabled -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ws-manager-unpriviledged
  labels:
    app: {{ template "gitpod.fullname" . }}
    component: ws-manager
    kind: role-binding
    stage: {{ .Values.installation.stage }}
subjects:
- kind: ServiceAccount
  name: ws-manager
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}-ns-psp:unprivileged
  apiGroup: rbac.authorization.k8s.io
{{ end }}