# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ $comp := .Values.components.wsProxy -}}
{{- if and (not $comp.disabled) (.Values.installNetworkPolicies) -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ws-proxy
  labels:
    app: {{ template "gitpod.fullname" . }}
    component: ws-proxy
    kind: networkpolicy
    stage: {{ .Values.installation.stage }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "gitpod.fullname" . }}
      component: ws-proxy
  policyTypes:
  - Ingress
  ingress:
  # Allow access to HTTP/HTTPS/SSH proxy ports from everywhere
  - ports:
    - protocol: TCP
      port: {{ $comp.ports.httpProxy.containerPort }}
    - protocol: TCP
      port: {{ $comp.ports.httpsProxy.containerPort }}
    - protocol: TCP
      port: {{ $comp.ports.ssh.containerPort }}
{{ end }}
