---
- name: Install dependencies
  apt:
    name: python3-pip
    update_cache: yes
    state: present
  become: true

- name: Install google Python library
  pip:
    name:
      - google-auth
      - google-cloud-storage
    state: present
  become: true

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  become: true
  loop:
    - /gitpod
    - /gitpod/manifests

- name: Create bucket
  google.cloud.gcp_storage_bucket:
    name: "{{ gcp.bucket_name }}"
    project: "{{ gcp.project }}"
    auth_kind: serviceaccount
    service_account_contents: "{{ gcp.cred_content }}"
    state: present

- name: Save K8s secrets
  shell: |
    kubectl get secret "{{ item.name }}" -n "{{ item.namespace }}" -o yaml > "/gitpod/manifests/{{ item.name }}.yaml" || rm -f "/gitpod/manifests/{{ item.name }}.yaml"
  loop:
    - name: https-certificates
      namespace: default
    - name: gitpod-issuer-account-key
      namespace: cert-manager

- name: Backup
  google.cloud.gcp_storage_object:
    action: upload
    bucket: "{{ gcp.bucket_name }}"
    src: "{{ item.local }}"
    dest: "{{ item.remote }}"
    project: "{{ gcp.project }}"
    auth_kind: serviceaccount
    service_account_contents: "{{ gcp.cred_content }}"
  ignore_errors: true
  loop:
    - remote: "https-certificates--{{ gitpod_domain }}.yaml"
      local: /gitpod/manifests/https-certificates.yaml
    - remote: "gitpod-issuer-account-key--{{ gitpod_domain }}.yaml"
      local: /gitpod/manifests/gitpod-issuer-account-key.yaml
