# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License-AGPL.txt in the project root for license information.

---
gcp_project: gitpod-self-hosted-testing
gcp_bucket_name: gitpod-self-hosted-testing-backups

gitlab_instance_name: gitlab
registry_instance_name: registry
