# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

gitpod:
  db:
    # 
    password: YourPasswordGoesHere

  components:
    db:
      gcloudSqlProxy:
        enabled: true
        # Set it to the name of your CloudSQL instance.
        instance: YourDBConnectionStringGoesHere
        credentials: secrets/your-key-file.json

  mysql:
    enabled: false