---
- name: Get installed services
  service_facts:

- name: Download k3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: 0755
  when: "'k3s.service' not in services"

- debug:
    var: hostvars.localhost.cluster_secret

- name: Install k3s
  environment:
    INSTALL_K3S_EXEC: "{{ (k3s_server_exec + ' ' + k3s_server_exec_labels + ((' ' + k3s_agent_exec_labels) if ('gitpod_total_nodes_1' in group_names) else '')) if ('gitpod_node_main' in group_names) else (k3s_agent_exec + ' ' + k3s_agent_exec_labels) }}"
    K3S_CLUSTER_SECRET: "{{ hostvars.localhost.cluster_secret }}"
    K3S_NODE_NAME: "{{ inventory_hostname }}"
    K3S_KUBECONFIG_MODE: "644"
    K3S_URL: "{{ ('gitpod_node_main' not in group_names) | ternary('https://' + node_prefix + '--node-0:6443', '') }}"
  command: /tmp/k3s-install.sh
  register: k3s_install_result
  when: "'k3s.service' not in services"

# - debug:
#     var: k3s_install_result

- name: Download Calico manifest
  get_url:
    url: https://docs.projectcalico.org/manifests/calico-vxlan.yaml
    dest: /tmp/calico.yaml
  when: "'gitpod_node_main' in group_names"

- name: Patch Calico manifest
  lineinfile:
    path: /tmp/calico.yaml
    insertafter: '"type": "calico",'
    line: '          "container_settings": { "allow_ip_forwarding": true },'
  when: "'gitpod_node_main' in group_names"

- name: Wait for the manifest folder
  wait_for:
    path: /var/lib/rancher/k3s/server/manifests
  become: true
  when: "'gitpod_node_main' in group_names"

- name: Install Calico manifest
  copy:
    remote_src: true
    src: /tmp/calico.yaml
    dest: /var/lib/rancher/k3s/server/manifests/calico.yaml
  become: true
  when: "'gitpod_node_main' in group_names"

- name: Install Cert Manager manifest
  copy:
    src: "{{ item }}"
    dest: /var/lib/rancher/k3s/server/manifests/
  with_fileglob: "cert-manager*.yaml"
  become: true
  when: "'gitpod_node_main' in group_names"

- name: Copy gitpod-config.k3s.yaml
  copy:
    src: gitpod-config.k3s.yaml
    dest: /gitpod/
  when: "'gitpod_node_main' in group_names"

- name: Patch Gitpod config
  shell: |
    yq eval-all --inplace 'select(fileIndex == 0) * select(fileIndex == 1)' /gitpod/gitpod-config.yaml /gitpod/gitpod-config.k3s.yaml
    yq eval --inplace ".domain = \"{{ gitpod_domain }}\"" /gitpod/gitpod-config.yaml
  when: "'gitpod_node_main' in group_names"

- name: Validate Gitpod config
  command: gitpod-installer validate config --config /gitpod/gitpod-config.yaml
  when: "'gitpod_node_main' in group_names"

- name: Copy manifests
  copy:
    src: /gitpod/manifests/
    remote_src: true
    dest: /var/lib/rancher/k3s/server/manifests/
  become: true
  when: "'gitpod_node_main' in group_names"

- name: Waiting for cluster validation
  shell: gitpod-installer validate cluster --kubeconfig /etc/rancher/k3s/k3s.yaml --config /gitpod/gitpod-config.yaml
  register: result
  until: result.rc == 0
  retries: 120
  delay: 5
  when: "'gitpod_node_main' in group_names"

- name: Render Gitpod manifests
  shell: gitpod-installer render --config /gitpod/gitpod-config.yaml > /var/lib/rancher/k3s/server/manifests/gitpod-manifests.yaml
  become: true
  when: "'gitpod_node_main' in group_names"
