# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License-AGPL.txt in the project root for license information.

---
gitpod_node_prefix: gitpod
gitpod_nodes_count: 3

gcp_project: "{{ undef(hint='You must specify your GCP project.') }}"
gcp_cred_content: "{{ lookup('file', '/service-account.json') }}"
gcp_zone: europe-west3-a
