pod:
  serviceAccount: werft
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: dev/workload
                operator: In
                values:
                  - "builds"
  volumes:
    - name: gcp-sa
      secret:
        secretName: gcp-sa-gitpod-dev-deployer
    - name: harvester-kubeconfig
      secret:
        secretName: harvester-kubeconfig
    - name: harvester-k3s-dockerhub-pull-account
      secret:
        secretName: harvester-k3s-dockerhub-pull-account
    - name: harvester-vm-ssh-keys
      secret:
        secretName: harvester-vm-ssh-keys
  containers:
    - name: build
      image: eu.gcr.io/gitpod-core-dev/dev/dev-environment:mads-leeway-v0.7.3.4
      workingDir: /workspace
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "2Gi"
          cpu: "1"
      volumeMounts:
        - name: gcp-sa
          mountPath: /mnt/secrets/gcp-sa
          readOnly: true
        - name: harvester-kubeconfig
          mountPath: /mnt/secrets/harvester-kubeconfig
      env:
        - name: LEEWAY_WORKSPACE_ROOT
          value: /workspace
        - name: HONEYCOMB_DATASET
          value: "werft"
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: honeycomb-api-key
              key: apikey
      command:
        - bash
        - -c
        - |
          sleep 1
          set -Eeuo pipefail

          sudo chown -R gitpod:gitpod /workspace

          (cd .werft && yarn install && mv node_modules ..) | werft log slice prep
          printf '{{ toJson . }}' > context.json

          npx ts-node .werft/platform-delete-preview-environment.ts
