pod:
  serviceAccount: werft
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: dev/workload
                operator: In
                values:
                  - "builds"
  volumes:
    - name: gcp-sa
      secret:
        secretName: gcp-sa-gitpod-dev-deployer
    - name: harvester-kubeconfig
      secret:
        secretName: harvester-kubeconfig
    - name: harvester-k3s-dockerhub-pull-account
      secret:
        secretName: harvester-k3s-dockerhub-pull-account
    - name: harvester-vm-ssh-keys
      secret:
        secretName: harvester-vm-ssh-keys
  containers:
    - name: build
      image: eu.gcr.io/gitpod-core-dev/dev/dev-environment:aa-fix-previewctl-get-name.0
      workingDir: /workspace
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: gcp-sa
          mountPath: /mnt/secrets/gcp-sa
          readOnly: true
        - name: harvester-kubeconfig
          mountPath: /mnt/secrets/harvester-kubeconfig
        - name: harvester-vm-ssh-keys
          mountPath: /mnt/secrets/harvester-vm-ssh-keys
        - name: harvester-k3s-dockerhub-pull-account
          mountPath: /mnt/secrets/harvester-k3s-dockerhub-pull-account
      env:
        - name: HONEYCOMB_DATASET
          value: "werft"
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: honeycomb-api-key
              key: apikey
      command:
        - bash
        - -c
        - |
          sleep 1
          set -Eeuo pipefail

          sudo chown -R gitpod:gitpod /workspace
          mkdir /workspace/.ssh
          cp /mnt/secrets/harvester-vm-ssh-keys/id_rsa /workspace/.ssh/id_rsa_harvester_vm
          cp /mnt/secrets/harvester-vm-ssh-keys/id_rsa.pub /workspace/.ssh/id_rsa_harvester_vm.pub
          sudo chmod 600 /workspace/.ssh/id_rsa_harvester_vm
          sudo chmod 644 /workspace/.ssh/id_rsa_harvester_vm.pub

          (cd .werft && yarn install && mv node_modules ..) | werft log slice prep
          printf '{{ toJson . }}' > context.json

          npx ts-node .werft/platform-delete-preview-environment.ts
