pod:
  serviceAccount: werft
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dev/workload
            operator: In
            values:
            - "builds"
  volumes:
  - name: gcp-sa
    secret:
      secretName: gcp-sa-gitpod-dev-deployer
  - name: gcp-sa-release
    secret:
      secretName: gcp-sa-gitpod-release-deployer
  containers:
  - name: build
    image: eu.gcr.io/gitpod-core-dev/dev/dev-environment:sje-add-kots.6
    workingDir: /workspace
    imagePullPolicy: Always
    volumeMounts:
    - name: gcp-sa
      mountPath: /mnt/secrets/gcp-sa
      readOnly: true
    - name: gcp-sa-release
      mountPath: /mnt/secrets/gcp-sa-release
      readOnly: true
    env:
    - name: WERFT_HOST
      value: "werft.werft.svc.cluster.local:7777"
    - name: HONEYCOMB_DATASET
      value: "werft"
    - name: HONEYCOMB_API_KEY
      valueFrom:
        secretKeyRef:
          name: honeycomb-api-key
          key: apikey
    command:
      - bash
      - -c
      - |
        sleep 1
        set -Eeuo pipefail

        sudo chown -R gitpod:gitpod /workspace

        (cd .werft && yarn install && mv node_modules ..) | werft log slice prep

        npx ts-node .werft/delete-preview-environments/delete-preview-environments-cron.ts
plugins:
  # Every hour at 15 minutes past. E.g. 10:15, 11:15, etc.
  cron: "15 * * * *"
