
components:
  proxy:
    disabled: true

  wsProxy:
    hostHeader: Host

  wsManagerBridge:
    disabled: true

  server:
    disabled: true

  messagebus:
    disabled: true

  dashboard:
    disabled: true

  dbMigrations:
    disabled: true

  db:
    autoMigrate: false

  imageBuilder:
    disabled: true

minio:
  enabled: false
  accessKey: EXAMPLEvalue
  secretKey: Someone.Should/ReallyChangeThisKey!!

mysql:
  enabled: false

registry-facade:
  enabled: false
