# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License-AGPL.txt in the project root for license information.

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQU5CQURFR21HWXNyVGVJV1JlYzJHeFl3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa09UWTFNemt4TjJVdE9UY3paQzAwWkRZMkxUZ3hPVE10WW1ZMFpETmtPRFJsWkdJMApNQjRYRFRJd01EY3lPREUyTVRVeE1Wb1hEVEkxTURjeU56RTNNVFV4TVZvd0x6RXRNQ3NHQTFVRUF4TWtPVFkxCk16a3hOMlV0T1RjelpDMDBaRFkyTFRneE9UTXRZbVkwWkROa09EUmxaR0kwTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdnAyakVuaTRHOXpCQ3lIM3hibU9Hdit4cnhtUjhmQTM1ZWFRelR6ZAppcXVkMENhbnRlbzFJaDUxMXVlcVFibkpxYWRiNDd0NDdsWFk2NHlXeUI1WnNFL3d4UXI3Nk9sUjVhaEFZYWJBCllLTi92ZjZXVWRvUW9KbUV4WElMc1packIwcUN6WllWV1MzbE45YXRCRmRGaGVYdTNSQWJOR1h6MGNmZ1A0YUIKMllsSmtMdFJvbTdLQlI0RXgyYWI3dGRscEF5VFhJWHVOWnJzODQzSFVBZXFvd2toQlE3UkVoR2o2RlJQa215RApTMUlwM1oxWGgzOXduZlA5S1Eyc3dNbXZZRGlRRUltQkIyQ09aMVBMNVV2T2MwQWp6ejVGWjNCWUlzREh3TXhnCnBLcHlhenNuVVNxeE5sd0hIUVhZU3ZCSHYwREhmejNWZTFWWGwxWXVucDJLVndJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpSVnVCRDhXNDZpcEFseFdidzNBbmhjMFR5SHdGZmVXclZNekhIb1pveGZxRWg2SU50eVZOMC9DOWJQSStCU2lqCjJnRGlEcDNDNm9lZ1RrWU51OTF2Tkw2MUlhcnI4ckpyNDNaVkZCTlpZbGs5Z2pWS2Joc2hCS0x4VjFHMWJnNVoKRC9xODVsdlZWZXBrUkFVTjJsQjg2VTd0RkVzQ09NUWpEMDFUNThOVUVqakNha1pNMkdCU091bHlOUi8rbHNBeAp0NXJ6NnRHWDY2Q3NnMGdUTEQwMksrajJ5KzRObzR2Z3NML1BMNkNUTVpVdHJ6L3FwWitrSGVnemJIUXJwQmVCCnFNaEUwRm5TWFh0Sk9idGhTL3NMZDJlN0JBcVp1STVmdURnZC9NZGNuVFM3MWVaaG80c0o5dDU3ZVFoQlJFOEwKeTdTS1dYTnBRb0lRRlE5VVRLS1h1QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.241.166.105
  name: gke_gitpod-core-dev_europe-west1-b_dev
contexts:
- context:
    cluster: gke_gitpod-core-dev_europe-west1-b_dev
    user: gke_gitpod-core-dev_europe-west1-b_dev
  name: dev
current-context: dev
kind: Config
preferences: {}
users:
- name: gke_gitpod-core-dev_europe-west1-b_dev
  user:
    auth-provider:
      name: gcp
