# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

gitpod:
  wsSync:
    remoteStorage:
      kind: minio
      minio:
        endpoint: minio:9000
        accessKey: EXAMPLEvalue
        secretKey: Someone.Should/ReallyChangeThisKey!!
        tmpdir: /tmp

  minio:
    enabled: false