apiVersion: v1
authProviders: []
blockNewUsers:
  enabled: false
  passlist: []
certificate:
  kind: secret
  name: https-certificates
containerRegistry:
  inCluster: true
  privateBaseImageAllowList: []
database:
  inCluster: true
disableDefinitelyGp: true
domain: ""
kind: Full
metadata:
  region: local
  shortname: default
objectStorage:
  inCluster: true
  resources:
    requests:
      memory: 2Gi
observability:
  logLevel: info
openVSX:
  url: https://open-vsx.org
repository: eu.gcr.io/gitpod-core-dev/build
workspace:
  maxLifetime: 36h0m0s
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
  runtime:
    containerdRuntimeDir: /var/lib/containerd/io.containerd.runtime.v2.task/k8s.io
    containerdSocket: /run/containerd/containerd.sock
    fsShiftMethod: shiftfs
