authProviders:
- id: "Local GitLab"
  host: "gitlab.$BASEDOMAIN"
  protocol: "https"
  type: "GitLab"
  oauth:
    clientId: "2ce8bfb95d9a1e0ed305427f35e10a6bdd1eef090b1890c68e5f8370782d05ee"
    clientSecret: "a5447d23643f7e71353d9fc3ad1c15464c983c47f6eb2e80dd37de28152de05e"
    callBackUrl: "https://gitpod.$BASEDOMAIN/auth/gitlab/callback"
    settingsUrl: "gitlab.$BASEDOMAIN/-/profile/applications"
