name: Build on Push
on: [push]

env:
  REGISTRY: ghcr.io
  DO_PUBLISH: "false"
  publishToNPM: "false"
  SEGMENT_IO_TOKEN: ""
  version: "devel"
  LEEWAY_WORKSPACE_ROOT: "/github/workspace"
  JAVA_HOME: "/home/gitpod/.sdkman/candidates/java/current"
  # components/dashboard:app need this
  CI: "false"

jobs:
  build-gitpod-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.APP }}
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: Filter test job 1
        shell: bash
        run: sed -i 's/[-] test[:]docker/#- test:docker/g' components/BUILD.yaml
      - name: Filter test job 2
        shell: bash
        run: find . | grep BUILD.yaml | xargs -n 1 sed -i 's/[-] [:]dbtest/#- :dbtest/g'
      - name: Change docker tag
        shell: bash
        run: find . | grep BUILD.yaml | xargs -n 1 sed -i 's/commit[-]/commit-amd64-/g'
      - name: Prevent permission error
        shell: bash
        run: sudo chmod 777 /var/run/docker.sock
      - name: check uname
        # https://github.com/gitpod-arm/workspace-images/pkgs/container/workspace-images%2Fgitpod-dev/14065438?tag=arm64 for amd64
        uses: docker pull ghcr.io/gitpod-arm/workspace-images/gitpod-dev:arm64@sha256:3738e57d85354de898b9ad9948ae6f83c0759ed81b2c92f4ded6f531c550bc4c
        with:
          args: |
            /bin/bash -c "uname -m"
      - name: build
        # https://github.com/gitpod-arm/workspace-images/pkgs/container/workspace-images%2Fgitpod-dev/14065438?tag=arm64 for amd64
        uses: docker pull ghcr.io/gitpod-arm/workspace-images/gitpod-dev:arm64@sha256:3738e57d85354de898b9ad9948ae6f83c0759ed81b2c92f4ded6f531c550bc4c
        with:
          args: |
            /bin/bash -c "sudo chown gitpod:gitpod -R /github/home/ && docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} && leeway -DSEGMENT_IO_TOKEN=${{ env.SEGMENT_IO_TOKEN }} -DpublishToNPM=${{ env.publishToNPM }} -DimageRepoBase=ghcr.io/gitpod-arm/gitpod -Dversion=${{ env.version }}-amd64 build components:all-docker --dont-test --dont-retag"

  build-gitpod-arm64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.APP }}
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: Filter test job 1
        shell: bash
        run: sed -i 's/[-] test[:]docker/#- test:docker/g' components/BUILD.yaml
      - name: Filter test job 2
        shell: bash
        run: find . | grep BUILD.yaml | xargs -n 1 sed -i 's/[-] [:]dbtest/#- :dbtest/g'
      - name: Change docker tag
        shell: bash
        run: find . | grep BUILD.yaml | xargs -n 1 sed -i 's/commit[-]/commit-amd64-/g'
      - name: Prevent permission error
        shell: bash
        run: sudo chmod 777 /var/run/docker.sock
      - name: check uname
        # https://github.com/gitpod-arm/workspace-images/pkgs/container/workspace-images%2Fgitpod-dev/14065438?tag=arm64 for arm64
        uses: docker://ghcr.io/gitpod-arm/workspace-images/gitpod-dev:arm64@sha256:9bcb27c3d13737c57a6b1c5791c62845ee37af0f28ae70a3fd31975d3510a9c7
        with:
          args: |
            /bin/bash -c "uname -m"
      - name: build
        # https://github.com/gitpod-arm/workspace-images/pkgs/container/workspace-images%2Fgitpod-dev/14065438?tag=arm64 for arm64
        uses: docker://ghcr.io/gitpod-arm/workspace-images/gitpod-dev:arm64@sha256:9bcb27c3d13737c57a6b1c5791c62845ee37af0f28ae70a3fd31975d3510a9c7
        with:
          args: |
            /bin/bash -c "sudo chown gitpod:gitpod -R /github/home/ && docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} && leeway -DSEGMENT_IO_TOKEN=${{ env.SEGMENT_IO_TOKEN }} -DpublishToNPM=${{ env.publishToNPM }} -DimageRepoBase=ghcr.io/gitpod-arm/gitpod -Dversion=${{ env.version }}-amd64 build components:all-docker --dont-test --dont-retag"
