name: Create ephemeral GCE VM

on:
  workflow_call:
    secrets:
      GCP_CREDENTIALS:
        required: true
      GH_SELF_HOSTED_RUNNER:
        required: true
    outputs:
      label:
        value: ${{ jobs.run.outputs.label }}

jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - id: gcloud-auth
        name: gcloud auth activate-service-account
        shell: bash
        run: |
          gcloud auth activate-service-account --key-file ${{ steps.auth.outputs.credentials_file_path }}
      - id: create-runner
        uses: gitpod-io/gce-github-runner@main
        with:
          token: ${{ secrets.GH_SELF_HOSTED_RUNNER }}
          project_id: gitpod-core-dev
          machine_zone: europe-west1-b
          repository: gitpod-io/gce-github-runner
